#!/bin/bash 
#SBATCH -J bgremove
#SBATCH -o /share/ju/urbanECG/log/bgremover/%j.out 
#SBATCH -e /share/ju/urbanECG/log/bgremover/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --get-user-env 
#SBATCH --mem=32gb
#SBATCH -t 400:00:00 
#SBATCH --partition=ju
#SBATCH --gpus=1

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/FastSAM

cd /share/ju/urbanECG/drivers/cv

python background-remover.py $1 $2