#!/bin/bash 
#SBATCH -J cropper
#SBATCH -o /share/ju/urbanECG/log/cropper/%j.out 
#SBATCH -e /share/ju/urbanECG/log/cropper/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --get-user-env 
#SBATCH --mem=64gb
#SBATCH -t 400:00:00 
#SBATCH --partition=ju
#SBATCH --gpus=1

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/urbanekg

cd /share/ju/urbanECG/drivers/processing

python cropper.py $1 $2