#!/bin/bash 
#SBATCH -J graph
#SBATCH -o /share/ju/urbanECG/log/graph/%j.out 
#SBATCH -e /share/ju/urbanECG/log/graph/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --get-user-env 
#SBATCH --mem=192gb
#SBATCH -t 400:00:00 
#SBATCH --partition=pierson

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/urbanekg

cd /share/ju/urbanECG/drivers/analysis

python graph.py