#!/bin/bash 
#SBATCH -J oai_inference
#SBATCH -o /share/ju/urbanECG/log/oai_inference/%j.out 
#SBATCH -e /share/ju/urbanECG/log/oai_inference/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --get-user-env 
#SBATCH --mem=32gb
#SBATCH -t 400:00:00
#SBATCH --partition=pierson

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/urbanekg.oai

cd /share/ju/urbanECG/drivers/cv/oai

python vision_inference.py
