#!/bin/bash 
#SBATCH -J parse
#SBATCH -o /share/ju/urbanECG/log/parse_detections/%j.out 
#SBATCH -e /share/ju/urbanECG/log/parse_detections/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --get-user-env 
#SBATCH --mem=64gb
#SBATCH -t 1:00:00
#SBATCH --partition=ju

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/urbanekg

cd /share/ju/urbanECG/src/processing

python parse_detections.py $1