#!/bin/bash 
#SBATCH -J pull_imgs_near_complaints
#SBATCH -o /share/ju/urbanECG/log/pull_imgs_near_complaints/%j.out 
#SBATCH -e /share/ju/urbanECG/log/pull_imgs_near_complaints/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --get-user-env 
#SBATCH --mem=32gb
#SBATCH -t 400:00:00 
#SBATCH --partition=ju

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/urbanekg

cd /share/ju/urbanECG/drivers/nyc_311

python pull_imgs_near_complaints.py