#!/bin/bash 
#SBATCH -J bdd_drivable_area_train
#SBATCH -o /share/ju/urbanECG/log/bdd_drivable_area_train/%j.out 
#SBATCH -e /share/ju/urbanECG/log/bdd_drivable_area_train/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --get-user-env 
#SBATCH --mem=32gb
#SBATCH --gpus=1
#SBATCH -t 400:00:00 
#SBATCH --partition=pierson

pwd
source /home/mwf62/.bashrc
 
source activate /share/ju/conda_virtualenvs/urbanekg.openmmlab

cd /share/ju/urbanECG/static/libraries/mmsegmentation

python tools/train.py projects/driveable_area_swin/configs/upernet_swin_bdd100k-720x1280.py --work-dir ./output_swin 